title = "Chris Kozak's Data Science Blog"
baseURL = "https://examiner-squirrel-16607.netlify.com/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Built with the Hugo Ananke theme"
  facebook = "https://www.facebook.com/christopher.kozak.92"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = "https://github.com/csk0083"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
