---
title: 'Visualizing Data Part 1: Box & Density Plots'
author: "Chris Kozak"
date: "September 15, 2017"
output: html_document
---



<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>This if the first of a five-part series of posts, in which we’ll go over some of the basics of querying data with dplyr, and building visualizations with ggplot2. These are two of the most popular packages from Hadley Wickham’s Tidyverse, which are all built with the same underlying principles and APIs. We’ll also compare and contrast the visualizations from the base R package with those from the ggplot2 package, and the different syntax required of the two packages.</p>
<pre class="r"><code>library(Lahman) #a comprehensive dataset of MLB statistics
library(nflscrapR) #contains NFL data and a built-in API for scraping the most recent data
library(dplyr) #package for querying data
library(ggplot2) #one of the best packages for data visualization
library(ggiraph) #extension that makes ggplot2 graphs interactive</code></pre>
</div>
<div id="boxplot" class="section level2">
<h2>Boxplot</h2>
<p>We’ll begin by creating simple visualizations of a one-dimensional distribution of data: MLB players’ weights. First, let’s take a quick peek at how this data is distributed using the <em>summary()</em> call.</p>
<pre class="r"><code>summary(Master$weight)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    65.0   170.0   185.0   186.4   200.0   320.0     854</code></pre>
<p><em>Master$weight</em> above specifies that we are selecting the <em>weight</em> column/vector from the <em>Master</em> table in the Lahman package, which we already loaded using the <em>library()</em> command. This presents a tidy set of statistics. We can quickly see the lightest MLB player ever weighed 65 pounds, while the heaviest weighed 320. Another useful features is that it tells us we have 854 missing cells of data (or NAs).</p>
<p>Now, let’s visualize this data using the boxplot command. We’ll begin by creating a relatively simply boxplot using base R’s <em>boxplot()</em> call.</p>
<pre class="r"><code>boxplot(x=Master$weight)</code></pre>
<p><img src="/ck650.netlify.com/post/p1_boxdensity_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>This generates a very bare-bones boxplot. Now, let’s run the <em>boxplot()</em> call again, but with a few more options to make a more appealing visualization. The <em>horizontal = TRUE</em> command flips the plot on its side, making it easier to read. <em>col</em> specifies a color, while <em>main</em> allows us to specify a title. Finally, <em>pch=20</em> changes the point character from the default large empty circle, to a small filled one.</p>
<pre class="r"><code>boxplot(x=Master$weight, horizontal = T, col = &quot;blue&quot;, main = &quot;Baseball players&#39; weights&quot;, pch=20)</code></pre>
<p><img src="/ck650.netlify.com/post/p1_boxdensity_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="density-plot" class="section level2">
<h2>Density plot</h2>
<p>Next, we’ll create a density plot using the base R package, and the same weight data we used in the previous visualization.</p>
<pre class="r"><code>weight2 &lt;- na.omit(Master$weight) #since plot(density()) won&#39;t work with NAs, we&#39;ll have to filter them out first
plot(density(weight2))</code></pre>
<p><img src="/ck650.netlify.com/post/p1_boxdensity_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>In our next post, we’ll go over histograms.</p>
</div>
